### ISSUE TITLE
1.x-2.x - After installing, clicking a forum gives a 404

### ISSUE THREAD

**Issue by laryn** [backdrop-contrib/forum#11]
After installing 1.x-2.x (and **Views_term_hierarchy**), I get a 404 error when I click on the default "General discussion" forum (from the main Structure >> Forums page). I get a forum list if I just go to `/forum` but then if I click on the "General discussion" forum from there I get the 404 again.

**Comment by docwilmot** [comment]
Thanks for reporting this. I will check asap. Did you by any chance have the 1.x version installed, and if so did you cache flush? (no idea if this would be any use, but worth suggesting till I can get to it to test).

**Comment by docwilmot** [comment]
Please also check if the Topics View is enabled on your site. The menu entry for the topic Views are supposed to be provided by the View itself. If youre getting 404 it should suggest that View config didnt install for some reason.

**Comment by laryn** [comment]
If I flush caches, I still get the 404 error. I don't think I had the 1.x version installed, however.

The `topic` view is enabled. Not sure if this relates, but when I click on "Configure" beside the `topic` view, I get an error. Via that link it is trying to load the `Topics` view which doesn't exist. Through the admin menu `Structure >> Views >> topic` things work as expected.

**Comment by docwilmot** [comment]
OK, thats helpful. A silly error by me. Again I made the mistake of renaming variables by search and replace and not retesting thoroughly before pushing. Thats twice today. Gimme an hour. Will fix.
