### ISSUE TITLE
Incorrect integer value: '' for column 'sticky' 

### ISSUE THREAD

**Issue by dkonle** [backdrop-contrib/forum#16]
I've installed the Backdrop discussion forum module (1.x-1.0.1) on Backdrop 1.12.4.
When logged in as administrator I can add a "new forum topics" but when logged in as just a registered user I get the error message "The website encountered an unexpected error. Please try again later" when trying to add a new topic. I've tried it on two different servers and get the same error. Under "Resent log messages" there are two errors:

1. "PHP EntityStorageException: SQLSTATE[HY000]: General error: 1366 Incorrect integer value: '' for column 'sticky' at row 1 in NodeStorageController->save() (line 320 of /var/www/html/concord/core/modules/node/node.entity.inc). "

2. "node PDOException: SQLSTATE[HY000]: General error: 1366 Incorrect integer value: '' for column 'sticky' at row 1: INSERT INTO {forum_index} (nid, title, tid, sticky, created, comment_count, last_comment_timestamp) VALUES (:db_insert_placeholder_0, :db_insert_placeholder_1, :db_insert_placeholder_2, :db_insert_placeholder_3, :db_insert_placeholder_4, :db_insert_placeholder_5, :db_insert_placeholder_6); Array ( [:db_insert_placeholder_0] => 105 [:db_insert_placeholder_1] => test [:db_insert_placeholder_2] => 11 [:db_insert_placeholder_3] => [:db_insert_placeholder_4] => 1552941735 [:db_insert_placeholder_5] => 0 [:db_insert_placeholder_6] => 1552941735 ) in forum_field_storage_pre_insert() (line 497 of /var/www/html/concord/modules/forum/forum.module)."

The following role permissions are checked for AUTHENTICATED user:

View comments
Post comments 
Skip comment approval
Use the Filtered HTML text format
View published content
Forum topic: Create new content
Forum topic: Edit own content
Forum topic: Delete own content

Is there more information I can provide or any other way I can help solve this problem.
Thank you Klonos for your quick reply in the Backdrop forum.

**Comment by herbdool** [comment]
I wonder if this error is related to "sticky" being optional now for nodes. @docwilmot thoughts? It's passing empty string instead of zero.

**Comment by herbdool** [comment]
@dkonle I've made a bug fix. If you're comfortable with testing please try out the main repo. If all goes well I or @docwilmot can make an official release.

**Comment by dkonle** [comment]
@herbdool  The forum module seems to be working fine now. Thank you very much! I really like Backdrop!
