### ISSUE TITLE
No "type = module" in forum.info file for the 1.0.0 release causes installation via Project installer to fail.

### ISSUE THREAD

**Issue by bd0bd** [backdrop-contrib/forum#3]
_Failed to install one project._

BD 1.4.3

Chrome

**Comment by klonos** [comment]
Does the same happen if you use another browser? If not, then try disabling your Chrome extensions to see if one of them is causing the issue.

**Comment by klonos** [comment]
Also, can you please try [the 1.x-2.x version](https://github.com/backdrop-contrib/forum/archive/1.x-2.x.zip)? We are working on that and intent to use it on backdropcms.org for running our official forum if it works for us (https://github.com/backdrop-ops/backdropcms.org/issues/250).

**Comment by bd0bd** [comment]
Browser is not the problem.

I install from /admin/modules/install and not via FTP.

**Comment by klonos** [comment]
Hm, it installs just fine for me. Any errors in the log (`/admin/reports/dblog`)?

Also, what environment? PHP version for example?

**Comment by bd0bd** [comment]
There was an error while installing Forum. The info file (temporary://update-extraction-a0c574d4/forum/forum.info) does not define a 'type' attribute.

5.6.22

**Comment by klonos** [comment]
From what I can see, the .info file does contain a `type = module` line: https://github.com/backdrop-contrib/forum/blob/1.x-1.x/forum.info#L3. Besides, I'm pretty sure that our packaging script throws an error if there is no type defined and no release file is created in that case.

Nevertheless, I confirm this bug when installing via the Project Installer (`/admin/modules/install`).

**Comment by klonos** [comment]
I confirm that the 1.0.0 zip file somehow has an older version of the .info file without `type = module`. @docwilmot can you please delete the release and re-tag so that we have a proper .info file with 1.0.0?

**Comment by bd0bd** [comment]
Now I have tried to install the new version of the forum.
The problem still exist.

**Comment by docwilmot** [comment]
fixed
