### ISSUE TITLE
Decide what to do when module uninstalled

### ISSUE THREAD

**Issue by docwilmot** [backdrop-contrib/forum#4]
Noticed yesterday that my local Forum install was broken. Turns out its because I un/reinstalled it to test something. Uninstalling a Forum probably doesnt happen very often so never noticed this.

The `forum.settings` config with the container info is deleted, so the module doesnt know how to recategorize stuff once you reinstall. I'm thinking drop the container concept and just use Forum vocabulary hierarchy to organize forums as suggested by @Gormartsen. That way reinstalling will pick up the existing hierarchy and Forum posts tagged with it.

But maybe if you uninstall, the old Forum posts should be deleted?

Reading on D.org lead to the following issue: https://www.drupal.org/node/2224581 where the Drupal team is considering completely purging all Forum data on uninstall. Not sure yet which is the best option.

Any more thoughts?

**Comment by klonos** [comment]
Forum posts are going to be content nodes. Right?

I don't know of any other module that deletes content upon uninstallation. Not that I'm objecting to that. Just pointing the fact.

**Comment by docwilmot** [comment]
> Forum nodes must be deleted before the module is uninstalled...

From the Drupal issue.

**Comment by herbdool** [comment]
I think it's a good practice _not_ to delete content automatically when uninstalling a module. Better that people manually delete so they can decide what content they want to save.

**Comment by klonos** [comment]
I tend to have the same view as @herbdool but did want to point the fact that removing/uninstalling 1.x and installing 2.x I ended up with 2 "General discussion" forums. Perhaps we should check for the existence of a forum with that label before creating the default (again/twice).

**Comment by docwilmot** [comment]
Agreed, lets not follow the Drupal practice just yet,
