### ISSUE TITLE
Progress update

### ISSUE THREAD

**Issue by docwilmot** [backdrop-contrib/forum#7]
- Finished removing container concept. See https://github.com/backdrop-contrib/forum/issues/6
- Added icon support, but using old default icons, which need changing. Also need to reconsider whether to add icons as a views column instead of as implemented now as a `<span>` element attached to the title.
- Made use of built-in Pathauto functionality to use aliases throughout, so no NID or TID shows in the UI.
  - forum topics are `forum/FORUM NAME`
  - threads are `thread/NODE TITLE`

**Comment by Gormartsen** [comment]
> Added icon support, but using old default icons, which need changing. Also need to reconsider whether to add icons as a views column instead of as implemented now as a <span> element attached to the title.

How about fontawesome icons instead of old one?

Check it out here: http://www.drupal.ru/forum

**Comment by docwilmot** [comment]
@Gormartsen I had looked at the drupal.ru forums before; very nice indeed. But in this case when I say "icon support" I meant the boring icons which show if there are new topics, unread topics etc, not really support for a icon per forum. Sorry to be unclear. 

But in either case with the forum listings being Views, I suppose one could add an image field on the taxonomy term and include the image in the Views listing and accomplish what you've got there. Just guessing here, never tried it, but don't see why not.

Only question is if this is likely to be a popular enough request to code it into the module.

**Comment by Gormartsen** [comment]
> if there are new topics, unread topics etc, not really support for a icon per forum. Sorry to be unclear.

Sorry, I was not clear as well.
Here is it:

<img width="1150" alt="screen shot 2016-07-20 at 3 51 13 pm" src="https://cloud.githubusercontent.com/assets/5018896/17000718/df829478-4e91-11e6-9744-54fddb1fc14b.png">
<img width="1150" alt="screen shot 2016-07-20 at 3 50 25 pm" src="https://cloud.githubusercontent.com/assets/5018896/17000722/e3311a18-4e91-11e6-866a-de865aa69e14.png">
<img width="394" alt="screen shot 2016-07-20 at 3 50 14 pm" src="https://cloud.githubusercontent.com/assets/5018896/17000725/e6963c6a-4e91-11e6-83a5-20595c320310.png">

It's icons for: read, unread, last time update, total topics, total messages, new messages, author...

**Comment by Gormartsen** [comment]
> I suppose one could add an image field on the taxonomy term and include the image in the Views listing and accomplish what you've got there.

I did almost like you said, but instead of uploading image, I defined extra field for container where I specify fontawesome icon.

But to make it more userfriendly, I would add select icon field, where a dropdown with fontawesome icons represented. 

From my forum admin expirience it is really heavy to find a proper image to forum section and using predefined awesome icons is live saver.

**Comment by docwilmot** [comment]
Got it.

> Only question is if this is likely to be a popular enough request to code it into the module.

What you think? could this be a contrib add-on separate module for the forum icons? I think the idea of using Fontawesome is awesome, but until we have it in core that would mean bundling Fontawesome, no? I wouldnt want to do that.

**Comment by Gormartsen** [comment]
I think forum should be contrib module by itself. 
There is contrib module for fontawesome: https://github.com/backdrop-contrib/font_awesome
And yes, fontawesome icon selector could be separated module (enabled by default?).

There is a chance that some users would not need it and will use custom solution.

Old icons are so out of date :(

**Comment by docwilmot** [comment]
OK I've done as much as I can now. Hopefully someone can design some prettier icons someday. And I've ported Statistics module so we can add a pageviews field through Views.

Eventually need to remove forum_index table, and there is one nasty issue with reinstalling, where the `taxonomy_forum` field isn't remove on uninstall and causes errors. Apparently this is a core issue with a module defining a field and also being responsible for creating an instance of it. There may be a fix somewhere, but can't manage now.

That's all for a while.

**Comment by klonos** [comment]
> OK I've done as much as I can now. Hopefully someone can design some prettier icons someday. And I've ported Statistics module so we can add a pageviews field through Views.

👍

**Comment by docwilmot** [comment]
> Apparently this is a core issue with a module defining a field and also being responsible for creating an instance of it.

See previous issue: https://github.com/backdrop/backdrop-issues/issues/1953

**Comment by laryn** [comment]
Removed spam link from @arunsahu2468

**Comment by klonos** [comment]
I have checked in forum.b.org and we seem to be using a custom `Borg Forum` module instead of this one. Wondering why that is?

Since that seems more production-ready and we have been using it for a while, wondering if we can port whatever changes here, so that we benefit the rest of the community. ...unless that module was a complete rewrite, in which case, we should still release it in contrib.
